background_opacity 0.9

font_family JetBrainsMono Nerd Font
font_size 12.0

# Post-punk palette
foreground            #C9C3B8
background            #08080A
cursor                 #9C793B
cursor_text_color      #08080A
selection_foreground   #DED8CE
selection_background   #5C4568
url_color              #607EAA

color0  #211D25
color1  #8E2632
color2  #3F5F8F
color3  #9C793B
color4  #3F5F8F
color5  #5C4568
color6  #4F6488
color7  #C9C3B8
color8  #4E4853
color9  #B63D4B
color10 #607EAA
color11 #BE9956
color12 #607EAA
color13 #8F6A8B
color14 #718DB5
color15 #DED8CE

enable_audio_bell no
scrollback_lines 5000
hide_window_decorations titlebar-only


tab_bar_style powerline
tab_powerline_style round
active_tab_foreground   #DED8CE
active_tab_background   #8E2632
inactive_tab_foreground #77717D
inactive_tab_background #17131A
