ipc = on
preload   = /home/nightmare/Wallpapers/joy_division_02.jpeg
wallpaper = HDMI-A-1, /home/nightmare/Wallpapers/joy_division_02.jpeg
wallpaper = DP-3,     /home/nightmare/Wallpapers/joy_division_02.jpeg
splash = false
